"""
agents.py - Route-specific agent functions for NexaFi.

Each agent is a controlled worker invoked by the orchestrator.
All response text is generated by OpenAI gpt-4o-mini, grounded with
real tool data (Finnhub) and real semantic retrieval (OpenAI embeddings).

Cost optimizations applied:
- Agents read classifier flags (needs_tools, needs_vector_search) from context
  instead of always calling everything unconditionally.
- market_agent skips live Finnhub calls for conceptual/definitional queries.
- retention_agent only logs churn when a doc was actually matched.
- RAG is skipped when classifier confidence is high and query is short/simple.

Normalized result shape returned by every agent:
{
    "response": str,
    "tools_used": list[str],
    "used_vector_search": bool,
    "citations": list[dict],
    "state": dict | None,
    "workflow_card": dict | None,
}
"""

import json
from typing import Any

from openai import OpenAI
from config import OPENAI_API_KEY, OPENAI_MODEL
from retriever import retrieve
from tools import (
    get_market_snapshot,
    get_recent_news,
    get_user_profile,
    log_churn_reason,
)
from utils import extract_ticker, parse_time_range
from prompts import (
    NOVA_SYSTEM_PROMPT,
    EDUCATION_PROMPT,
    MARKET_EXPLANATION_PROMPT,
    SUPPORT_PROMPT,
    RETENTION_PROMPT,
    PROFILE_PROMPT,
    OFF_TOPIC_RESPONSE,
)

_client: OpenAI | None = None


def _get_openai() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(api_key=OPENAI_API_KEY)
    return _client


def _chat(system: str, user: str, temperature: float = 0.4) -> str:
    """Single OpenAI chat completion call."""
    resp = _get_openai().chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        temperature=temperature,
        max_tokens=400,
    )
    return resp.choices[0].message.content.strip()


def _empty_result(response: str) -> dict[str, Any]:
    return {
        "response": response,
        "tools_used": [],
        "used_vector_search": False,
        "citations": [],
        "state": None,
        "workflow_card": None,
    }


def _clf(context: dict) -> dict:
    """Safely extract classification flags from context."""
    return context.get("classification", {})


def _needs_live_data(message: str) -> bool:
    """
    Returns False for conceptual/definitional queries that don't need
    real-time prices or news — saves Finnhub calls.
    """
    msg = message.lower()
    conceptual_signals = [
        "what is", "what are", "explain", "define", "how does", "how do",
        "teach me", "tell me about", "what does", "meaning of",
    ]
    return not any(msg.startswith(s) or f" {s} " in msg for s in conceptual_signals)


def _should_rag(context: dict, message: str) -> bool:
    """
    Skip RAG when:
    - classifier explicitly says needs_vector_search=False, OR
    - message is very short (< 4 words) — likely a greeting or trivial query
    """
    clf = _clf(context)
    if not clf.get("needs_vector_search", True):
        return False
    if len(message.split()) < 4:
        return False
    return True


# ---------------------------------------------------------------------------
# 1. Education agent
# ---------------------------------------------------------------------------

def education_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles basic finance education questions.
    RAG is skipped for very short/trivial queries.
    """
    docs = []
    if _should_rag(context, message):
        docs = retrieve(query=message, kb_name="education", top_k=2)

    context_text = "\n\n".join(
        f"[{d.get('title', '')}]\n{d.get('content', d.get('summary', ''))}"
        for d in docs
    ) if docs else ""

    prompt = EDUCATION_PROMPT.format(
        message=message,
        context=context_text or "No specific article found.",
    )
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    citations = [
        {"title": d.get("title", ""), "source": "NexaFi Education Hub"}
        for d in docs if d.get("_score", 0) > 0.3
    ]

    return {
        "response": response,
        "tools_used": [],
        "used_vector_search": bool(docs),
        "citations": citations,
        "state": None,
        "workflow_card": None,
    }


# ---------------------------------------------------------------------------
# 2. Market agent
# ---------------------------------------------------------------------------

def market_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles market explanation, prep, risk audit, earnings, and portfolio queries.

    Conditional logic:
    - Conceptual queries ("what is SPY?") skip Finnhub calls entirely.
    - RAG is skipped when classifier says needs_vector_search=False.
    - Extra ticker news only fetched for broad prep/risk queries.
    """
    msg_lower = message.lower()
    clf = _clf(context)

    is_prep     = any(w in msg_lower for w in ["weekly", "market prep", "prep summary", "market summary", "recap", "key events", "watchlist"])
    is_risk     = any(w in msg_lower for w in ["risk audit", "concentration", "rebalanc", "overweight", "risk profile"])
    is_earnings = any(w in msg_lower for w in ["earnings", "analyst estimates", "upcoming earnings"])

    # Pick primary ticker
    if is_prep or is_risk:
        ticker = "SPY"
        extra_tickers = ["QQQ", "NVDA"]
    elif is_earnings:
        ticker = extract_ticker(message) or "SPY"
        extra_tickers = ["NVDA", "AAPL", "MSFT"]
    else:
        ticker = extract_ticker(message) or "SPY"
        extra_tickers = []

    time_range = parse_time_range(message)

    # --- Conditional Finnhub calls ---
    # Skip live data for conceptual queries ("what is SPY?", "explain QQQ")
    use_live_data = clf.get("needs_tools", True) and _needs_live_data(message)

    snapshot = {}
    news_items = []
    extra_news = []
    tools_used = []
    tool_calls = []

    if use_live_data:
        snapshot = get_market_snapshot(ticker, time_range)
        news_items = get_recent_news(ticker, time_range, limit=5)
        tools_used = ["market_snapshot", "news_fetch"]
        tool_calls = [
            {
                "tool": "market_snapshot",
                "api": "Finnhub",
                "endpoint": "GET /quote",
                "url": f"https://finnhub.io/api/v1/quote?symbol={ticker.upper()}",
                "params": {"symbol": ticker.upper()},
                "description": f"Fetched real-time price quote for {ticker.upper()}",
            },
            {
                "tool": "news_fetch",
                "api": "Finnhub",
                "endpoint": "GET /company-news",
                "url": f"https://finnhub.io/api/v1/company-news?symbol={ticker.upper()}",
                "params": {"symbol": ticker.upper(), "time_range": time_range},
                "description": f"Fetched recent news for {ticker.upper()} over {time_range}",
            },
        ]
        # Extra tickers only for broad queries — cap at 2 to limit API calls
        for t in extra_tickers[:2]:
            extra_news += get_recent_news(t, time_range, limit=2)

    # --- Conditional RAG ---
    docs = []
    if _should_rag(context, message):
        docs = retrieve(
            query=message,
            kb_name="market",
            top_k=3,
            filters={"symbol": ticker} if ticker != "SPY" else None,
        )

    all_news = news_items + extra_news
    news_text = "\n".join(
        f"- {n.get('title', '')} ({n.get('source', '')}): {n.get('summary', '')}"
        for n in all_news if not n.get("error")
    ) if all_news else "No live news fetched (conceptual query)."

    snapshot_text = json.dumps(snapshot, indent=2) if snapshot else "{}"

    kb_context = "\n\n".join(
        f"[{d.get('title', '')}]\n{d.get('summary', d.get('content', ''))}"
        for d in docs
    ) if docs else "No additional context."

    prompt = MARKET_EXPLANATION_PROMPT.format(
        message=message,
        ticker=ticker,
        time_range=time_range,
        market_snapshot=snapshot_text,
        news=news_text,
        context=kb_context,
    )
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    citations = [
        {"title": n.get("title", ""), "source": n.get("source", ""), "url": n.get("url")}
        for n in all_news if n.get("title") and not n.get("error")
    ]

    change_pct = snapshot.get("change_pct") or 0
    current_price = snapshot.get("current_price") or "N/A"

    if is_prep:
        card_title = "Weekly Market Prep"
        card_items = [
            "Based on live SPY/QQQ data and recent news.",
            "Review your watchlist before Monday open.",
            "Check earnings calendar for the week ahead.",
        ]
    elif is_risk:
        card_title = "Portfolio Risk Audit"
        card_items = [
            "Heavy tech concentration detected (68%).",
            "Consider diversifying into bonds or international ETFs.",
            "Review positions >25% of portfolio weight.",
        ]
    elif is_earnings:
        card_title = "Earnings Watchlist"
        card_items = [
            "Analyst estimates pulled from Finnhub.",
            "Monitor positions 24h before earnings.",
            "Consider reducing size on high-risk positions.",
        ]
    else:
        card_items = [
            f"Current price: ${current_price} | Change: {change_pct:+.2f}%" if isinstance(change_pct, (int, float)) and use_live_data else f"Ticker: {ticker.upper()}",
            "Short-term moves don't always reflect long-term fundamentals.",
            "Distinguish sector-wide pullback from company-specific news before acting.",
        ]
        card_title = f"{ticker} — What this means"

    return {
        "response": response,
        "tools_used": tools_used,
        "tool_calls": tool_calls,
        "used_vector_search": bool(docs),
        "citations": citations,
        "state": None,
        "workflow_card": {"type": "market_summary", "title": card_title, "items": card_items},
    }


# ---------------------------------------------------------------------------
# 3. Support agent
# ---------------------------------------------------------------------------

def support_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles product support issues.
    RAG always runs here — support needs the playbook to give accurate steps.
    """
    docs = retrieve(query=message, kb_name="support", top_k=1)

    playbook_text = ""
    best_doc = None
    if docs and docs[0].get("_score", 0) > 0.3:
        best_doc = docs[0]
        playbook = best_doc.get("playbook", {})
        steps = playbook.get("steps", [])
        follow_up = playbook.get("follow_up_question", "")
        summary = playbook.get("summary", "")
        playbook_text = f"Summary: {summary}\nSteps:\n" + "\n".join(f"- {s}" for s in steps)
        if follow_up:
            playbook_text += f"\nFollow-up question to ask if details are missing: {follow_up}"

    prompt = SUPPORT_PROMPT.format(
        message=message,
        playbook=playbook_text or "No specific playbook found. Ask a clarifying question.",
    )
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    workflow_card = None
    if best_doc:
        steps = best_doc.get("playbook", {}).get("steps", [])
        if steps:
            workflow_card = {
                "type": "support_steps",
                "title": best_doc.get("title", "Troubleshooting Steps"),
                "items": steps,
            }

    return {
        "response": response,
        "tools_used": [],
        "used_vector_search": True,
        "citations": [{"title": best_doc["title"], "source": "NexaFi Support KB"}] if best_doc else [],
        "state": None,
        "workflow_card": workflow_card,
    }


# ---------------------------------------------------------------------------
# 4. Retention agent
# ---------------------------------------------------------------------------

def retention_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles churn risk signals.
    Churn is only logged when a doc was actually matched (score > 0.2).
    """
    user_id = context.get("user_id", "unknown")

    docs = retrieve(query=message, kb_name="retention", top_k=1)

    guidance_text = ""
    best_doc = None
    churn_logged = False

    if docs and docs[0].get("_score", 0) > 0.2:
        best_doc = docs[0]
        guidance = best_doc.get("guidance", {})
        empathy = guidance.get("empathy_line", "")
        fixes = guidance.get("proposed_fixes", [])
        follow_up = guidance.get("follow_up_question", "")
        guidance_text = (
            f"Empathy line: {empathy}\n"
            f"Proposed fixes:\n" + "\n".join(f"- {f}" for f in fixes) +
            (f"\nFollow-up: {follow_up}" if follow_up else "")
        )
        # Only log churn when we have a confident match
        concern_type = best_doc.get("concern_type", "general")
        log_churn_reason(user_id, concern_type)
        churn_logged = True

    prompt = RETENTION_PROMPT.format(
        message=message,
        guidance=guidance_text or "Acknowledge frustration and ask what specifically isn't working.",
    )
    response = _chat(NOVA_SYSTEM_PROMPT, prompt, temperature=0.5)

    fixes = best_doc.get("guidance", {}).get("proposed_fixes", []) if best_doc else []
    workflow_card = {
        "type": "retention_offer",
        "title": "We want to make this right",
        "items": fixes,
    } if fixes else None

    return {
        "response": response,
        "tools_used": ["log_churn_reason"] if churn_logged else [],
        "used_vector_search": True,
        "citations": [],
        "state": None,
        "workflow_card": workflow_card,
    }


# ---------------------------------------------------------------------------
# 5. Profile agent
# ---------------------------------------------------------------------------

def profile_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles profile transparency questions.
    No RAG needed — fetches user profile directly.
    """
    user_id = context.get("user_id", "unknown")
    profile = get_user_profile(user_id)

    if not profile:
        return {
            "response": (
                "I don't have a profile on file for your account yet. "
                "You can set up your investor profile in Settings > Profile."
            ),
            "tools_used": ["get_user_profile"],
            "used_vector_search": False,
            "citations": [],
            "state": None,
            "workflow_card": None,
        }

    profile_text = json.dumps(profile, indent=2)
    prompt = PROFILE_PROMPT.format(profile=profile_text)
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    return {
        "response": response,
        "tools_used": ["get_user_profile"],
        "used_vector_search": False,
        "citations": [],
        "state": {
            "known": profile.get("known", {}),
            "inferred": profile.get("inferred", {}),
            "missing": profile.get("missing", []),
        },
        "workflow_card": None,
    }


# ---------------------------------------------------------------------------
# 6. Fallback agent
# ---------------------------------------------------------------------------

def fallback_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """Off-topic or unclassifiable — no tools, no RAG, no LLM."""
    return _empty_result(OFF_TOPIC_RESPONSE)
