"""
agents.py - Route-specific agent functions for NexaFi.

Each agent is a controlled worker invoked by the orchestrator.
All response text is generated by OpenAI gpt-4o-mini, grounded with
real tool data (Finnhub) and real semantic retrieval (OpenAI embeddings).

Normalized result shape returned by every agent:
{
    "response": str,
    "tools_used": list[str],
    "used_vector_search": bool,
    "citations": list[dict],
    "state": dict | None,
    "workflow_card": dict | None,
}
"""

import json
from typing import Any

from openai import OpenAI
from config import OPENAI_API_KEY, OPENAI_MODEL
from retriever import retrieve
from tools import (
    get_market_snapshot,
    get_recent_news,
    get_user_profile,
    log_churn_reason,
)
from utils import extract_ticker, parse_time_range
from prompts import (
    NOVA_SYSTEM_PROMPT,
    EDUCATION_PROMPT,
    MARKET_EXPLANATION_PROMPT,
    SUPPORT_PROMPT,
    RETENTION_PROMPT,
    PROFILE_PROMPT,
    OFF_TOPIC_RESPONSE,
)

_client: OpenAI | None = None


def _get_openai() -> OpenAI:
    global _client
    if _client is None:
        _client = OpenAI(api_key=OPENAI_API_KEY)
    return _client


def _chat(system: str, user: str, temperature: float = 0.4) -> str:
    """Single OpenAI chat completion call."""
    resp = _get_openai().chat.completions.create(
        model=OPENAI_MODEL,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        temperature=temperature,
        max_tokens=600,
    )
    return resp.choices[0].message.content.strip()


def _empty_result(response: str) -> dict[str, Any]:
    return {
        "response": response,
        "tools_used": [],
        "used_vector_search": False,
        "citations": [],
        "state": None,
        "workflow_card": None,
    }


# ---------------------------------------------------------------------------
# 1. Education agent
# ---------------------------------------------------------------------------

def education_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles basic finance education questions.
    Retrieves relevant KB docs via semantic search, then asks OpenAI to
    generate a clear, grounded explanation.
    """
    docs = retrieve(query=message, kb_name="education", top_k=2)
    context_text = "\n\n".join(
        f"[{d.get('title', '')}]\n{d.get('content', d.get('summary', ''))}"
        for d in docs
    )

    prompt = EDUCATION_PROMPT.format(message=message, context=context_text or "No specific article found.")
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    citations = [
        {"title": d.get("title", ""), "source": "NexaFi Education Hub"}
        for d in docs if d.get("_score", 0) > 0.3
    ]

    return {
        "response": response,
        "tools_used": [],
        "used_vector_search": True,
        "citations": citations,
        "state": None,
        "workflow_card": None,
    }


# ---------------------------------------------------------------------------
# 2. Market agent
# ---------------------------------------------------------------------------

def market_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles market explanation questions.
    Fetches real Finnhub data + news, retrieves semantic KB context,
    then generates a grounded explanation via OpenAI.
    """
    ticker = extract_ticker(message) or "SPY"
    time_range = parse_time_range(message)

    snapshot = get_market_snapshot(ticker, time_range)
    news_items = get_recent_news(ticker, time_range, limit=5)
    tools_used = ["market_snapshot", "news_fetch"]

    docs = retrieve(
        query=message,
        kb_name="market",
        top_k=3,
        filters={"symbol": ticker} if ticker != "SPY" else None,
    )

    news_text = "\n".join(
        f"- {n.get('title', '')} ({n.get('source', '')}): {n.get('summary', '')}"
        for n in news_items if not n.get("error")
    )
    snapshot_text = json.dumps(snapshot, indent=2)

    kb_context = "\n\n".join(
        f"[{d.get('title', '')}]\n{d.get('summary', d.get('content', ''))}"
        for d in docs
    )

    prompt = MARKET_EXPLANATION_PROMPT.format(
        message=message,
        ticker=ticker,
        time_range=time_range,
        market_snapshot=snapshot_text,
        news=news_text or "No recent news found.",
        context=kb_context or "No additional context.",
    )
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    citations = [
        {"title": n.get("title", ""), "source": n.get("source", ""), "url": n.get("url")}
        for n in news_items if n.get("title") and not n.get("error")
    ]

    change_pct = snapshot.get("change_pct") or 0
    current_price = snapshot.get("current_price") or "N/A"

    workflow_card = {
        "type": "market_summary",
        "title": f"{ticker} — What this means",
        "items": [
            f"Current price: ${current_price} | Change: {change_pct:+.2f}%" if isinstance(change_pct, (int, float)) else f"Current price: ${current_price}",
            "Short-term moves don't always reflect long-term fundamentals.",
            "Distinguish sector-wide pullback from company-specific news before acting.",
        ],
    }

    return {
        "response": response,
        "tools_used": tools_used,
        "used_vector_search": bool(docs),
        "citations": citations,
        "state": None,
        "workflow_card": workflow_card,
    }


# ---------------------------------------------------------------------------
# 3. Support agent
# ---------------------------------------------------------------------------

def support_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles product support issues.
    Retrieves the best-matching support playbook, then uses OpenAI to
    generate a clear, empathetic troubleshooting response.
    """
    docs = retrieve(query=message, kb_name="support", top_k=1)

    playbook_text = ""
    best_doc = None
    if docs and docs[0].get("_score", 0) > 0.3:
        best_doc = docs[0]
        playbook = best_doc.get("playbook", {})
        steps = playbook.get("steps", [])
        follow_up = playbook.get("follow_up_question", "")
        summary = playbook.get("summary", "")
        playbook_text = f"Summary: {summary}\nSteps:\n" + "\n".join(f"- {s}" for s in steps)
        if follow_up:
            playbook_text += f"\nFollow-up question to ask if details are missing: {follow_up}"

    prompt = SUPPORT_PROMPT.format(
        message=message,
        playbook=playbook_text or "No specific playbook found. Ask a clarifying question.",
    )
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    workflow_card = None
    if best_doc:
        playbook = best_doc.get("playbook", {})
        steps = playbook.get("steps", [])
        if steps:
            workflow_card = {
                "type": "support_steps",
                "title": best_doc.get("title", "Troubleshooting Steps"),
                "items": steps,
            }

    return {
        "response": response,
        "tools_used": [],
        "used_vector_search": True,
        "citations": [{"title": best_doc["title"], "source": "NexaFi Support KB"}] if best_doc else [],
        "state": None,
        "workflow_card": workflow_card,
    }


# ---------------------------------------------------------------------------
# 4. Retention agent
# ---------------------------------------------------------------------------

def retention_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles churn risk signals.
    Retrieves retention guidance, generates an empathetic response via OpenAI,
    and logs the churn signal.
    """
    user_id = context.get("user_id", "unknown")

    docs = retrieve(query=message, kb_name="retention", top_k=1)

    guidance_text = ""
    best_doc = None
    if docs and docs[0].get("_score", 0) > 0.2:
        best_doc = docs[0]
        guidance = best_doc.get("guidance", {})
        empathy = guidance.get("empathy_line", "")
        fixes = guidance.get("proposed_fixes", [])
        follow_up = guidance.get("follow_up_question", "")
        guidance_text = (
            f"Empathy line: {empathy}\n"
            f"Proposed fixes:\n" + "\n".join(f"- {f}" for f in fixes) +
            (f"\nFollow-up: {follow_up}" if follow_up else "")
        )

    prompt = RETENTION_PROMPT.format(
        message=message,
        guidance=guidance_text or "Acknowledge frustration and ask what specifically isn't working.",
    )
    response = _chat(NOVA_SYSTEM_PROMPT, prompt, temperature=0.5)

    concern_type = best_doc.get("concern_type", "general") if best_doc else "general"
    log_churn_reason(user_id, concern_type)

    fixes = best_doc.get("guidance", {}).get("proposed_fixes", []) if best_doc else []
    workflow_card = {
        "type": "retention_offer",
        "title": "We want to make this right",
        "items": fixes,
    } if fixes else None

    return {
        "response": response,
        "tools_used": ["log_churn_reason"],
        "used_vector_search": True,
        "citations": [],
        "state": None,
        "workflow_card": workflow_card,
    }


# ---------------------------------------------------------------------------
# 5. Profile agent
# ---------------------------------------------------------------------------

def profile_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles profile transparency questions.
    Fetches real user profile and uses OpenAI to explain it clearly.
    """
    user_id = context.get("user_id", "unknown")
    profile = get_user_profile(user_id)

    if not profile:
        return {
            "response": (
                "I don't have a profile on file for your account yet. "
                "You can set up your investor profile in Settings > Profile."
            ),
            "tools_used": ["get_user_profile"],
            "used_vector_search": False,
            "citations": [],
            "state": None,
            "workflow_card": None,
        }

    profile_text = json.dumps(profile, indent=2)
    prompt = PROFILE_PROMPT.format(profile=profile_text)
    response = _chat(NOVA_SYSTEM_PROMPT, prompt)

    return {
        "response": response,
        "tools_used": ["get_user_profile"],
        "used_vector_search": False,
        "citations": [],
        "state": {
            "known": profile.get("known", {}),
            "inferred": profile.get("inferred", {}),
            "missing": profile.get("missing", []),
        },
        "workflow_card": None,
    }


# ---------------------------------------------------------------------------
# 6. Fallback agent
# ---------------------------------------------------------------------------

def fallback_agent(message: str, context: dict[str, Any]) -> dict[str, Any]:
    """
    Handles off-topic or unclassifiable messages.
    No tools, no retrieval — just a polite redirect.
    """
    return _empty_result(OFF_TOPIC_RESPONSE)
